### Home
GET http://localhost:3000
### Get all students
GET http://localhost:3000/students
### Get one student by ID
GET http://localhost:3000/students/64695d3ebe7b2c3d98507566
### create student 
POST http://localhost:3000/students
Content-Type: application/json

{
    "primerNombre": "McKay",
    "apellidos": "Thomas",
    "grado": 3,
    "seccion": "A"
}
### Get all students of a grade and section
GET http://localhost:3000/students/grado
Content-Type: application/json

{
    "grado": 5,
    "seccion": "A"
}
### api-docs
GET http://localhost:3000/api-docs
###
DELETE http://localhost:3000/students/64695d3ebe7b2c3d98507572
###
PUT http://localhost:3000/students/64695d3ebe7b2c3d98507572
Content-Type: application/json

{
    "primerNombre": "John",
    "apellidos": "Smith",
    "grado": 4,
    "seccion": "A"
}


### RENDER TESTING
### Render home
GET https://vgh-records.onrender.com
### Render get students
GET https://vgh-records.onrender.com/students
### Render get one student
GET https://vgh-records.onrender.com/students/64695d3ebe7b2c3d98507576
### Render add new student
POST https://vgh-records.onrender.com/students
Content-Type: application/json
{
    "primerNombre": "McKay",
    "apellidos": "Thomas",
    "grado": 3,
    "seccion": "A"
}
### Render get class
GET https://vgh-records.onrender.com/students/grado
Content-Type: application/json
{
    "grado": 5,
    "seccion": "A"
}
### Render api-docs
GET https://vgh-records.onrender.com/api-docs
### Render
DELETE https://vgh-records.onrender.com/students/64695d3ebe7b2c3d98507576
### Render
PUT https://vgh-records.onrender.com/students/64695d3ebe7b2c3d98507576
Content-Type: application/json

{
    "primerNombre": "44343",
    "apellidos": "Smith",
    "grado": 4,
    "seccion": "D"
}
